### PR TITLE
Remove unneeded async from mock-server.js

### LINKED ISSUE #369: Build fails with latest Babel.js
Babel.js v7.11.1 [was released earlier today](https://github.com/babel/babel/releases/tag/v7.11.1) and since then in our build we see errors like
```
04-Aug-2020 22:22:26 | cleaning up...
-- | --
04-Aug-2020 22:22:26 | Build Error (broccoli-persistent-filter:Babel > [Babel: ember-cli-fastboot-testing]) in ember-cli-fastboot-testing/test-support/-private/mock-server.js
04-Aug-2020 22:22:26 |  
04-Aug-2020 22:22:26 | /opt/bamboo_homes/bamboo-home1/xml-data/build-dir/GLOBE-UAF48-RATE/packages/agwa/ember-cli-fastboot-testing/test-support/-private/mock-server.js: Unexpected token (19:11)
04-Aug-2020 22:22:26 |  
04-Aug-2020 22:22:26 | 17 \|
04-Aug-2020 22:22:26 | 18 \| export let mockServer = {
04-Aug-2020 22:22:26 | > 19 \|   async get(path, response, status = 200) {
04-Aug-2020 22:22:26 | \|            ^
04-Aug-2020 22:22:26 | 20 \|     return createMock(path, "GET", status, response);
04-Aug-2020 22:22:26 | 21 \|   },
04-Aug-2020 22:22:26 | 22 \|
04-Aug-2020 22:22:26 |  
04-Aug-2020 22:22:26 |  
04-Aug-2020 22:22:26 | Stack Trace and Error Report: /tmp/error.dump.56b192bda8efa3169008d27ec1477668.log
```

[Same error is reproducible via Babel REPL](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAG2PAthAxgawMrCgNzzgF44BvAKDjgEMBnATwDt04BzZACjBpgAsANHCjA6kJnWBC6MXgFc6JOACYADKoCU5KtWHI5UJnHQjewALIZM3XoLgAiAOIBRACr3psmAqEixECWANAG4dAF8BCh16ZlZIGRt-X1FxSU95RVI1TW1dPW9DY1MYCytEu3sABQB5bHd07zpk_0CQ8MjoxhY4Hhh0PnLm1Kk4GQylbK1KPJECoxNgM0ssQYdKgEFXAGEACQ9Rrx89Fsk26gio6hjusDkYVb9hhoUJ9SmdalmDeeLSld6KpUAKr1A4ZIYBU6hc4dK5dVgAE2ASBKDxSkJGY0arxy010X0KCyWZQBQnsABFnAAZNzOfZYo6PDFnOAXTqxYxIGhMIFgTjvGb6QoAM2Q_U4AHIAPQAfRl6C5TDkYAAtGgsHQJSywhQwsEgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.11.1&externalPlugins=).

I think it fails because [async getters are not a thing in JavaScript](https://github.com/tc39/ecmascript-asyncawait/issues/15).

### PR DESCRIPTION
**Pull request by SergeAstapov**
Fixes #369

### CODE REVIEW

File: addon-test-support/-private/mock-server.js [hunk 1]
```diff
@@ -25,27 +25,27 @@ let createMock = async function(path, method, statusCode, response) {
 }
 
 export let mockServer = {
-  async get(path, response, status = 200) {
```
Comment (SergeAstapov) [inline addon-test-support/-private/mock-server.js:28]: without `await` in the method `async` keyword does make any difference

File: addon-test-support/-private/mock-server.js [hunk 2]
```diff
@@ -9,7 +9,7 @@ let createMock = async function(path, method, statusCode, response) {
     path = `${url.pathname}${url.search}`;
   }
 
-  return await fetch('/__mock-request', {
+  return fetch('/__mock-request', {
```
Comment (SergeAstapov) [inline addon-test-support/-private/mock-server.js:12]: `fetch` returns a promise, so does not seem make any sense to have `await` as no result or error handling takes place

**Comment by SergeAstapov** [comment]
Hi @ryanto! Unless I'm missing anything, do you mind to release a new version once this get merged?

**Comment by ryanto** [comment]
Hey @SergeAstapov this looks good. Thanks for the PR!

File: addon-test-support/-private/mock-server.js (hunk 1 above)
Comment (adong) [reply addon-test-support/-private/mock-server.js:28]: I had similar issue from ember 3.16,  and I think it could be rewrite from

```javascript
async get(path, response, status = 200) {
```

to

```javascript
get: async function(path, response, status = 200) {
```

See: https://github.com/screwdriver-cd/ui/pull/576#issuecomment-668887311

Comment (SergeAstapov) [reply addon-test-support/-private/mock-server.js:28]: @adong yeah, that's an option - however async is just not needed here as there is no `await` in the method body
